@api = http://localhost:8080/api

### POST
POST {{api}}/users/login/vlad
Content-Type: application/json

{
    "password": "123456"
}

### POST
POST {{api}}/users/signUp
Content-Type: application/json

{
    "username": "vlad",
    "password": "123456",
    "email": "vlad@gmail.com"
}

