@api = http://localhost:8080/api

### POST
POST {{api}}/users/login/vlad
Content-Type: application/json

{
    "password": "123456"
}

### POST
POST {{api}}/users/signUp
Content-Type: application/json

{
    "id": 0,
    "username": "anonim",
    "password": "1",
    "email": "anonim@gmail.com"
}

### GET
GET {{api}}/users

